### ISSUE TITLE
Add support for ARM NEON

### ISSUE THREAD

**Issue by lemire** [fwessels/simdjson-go#1]
:-)

**Comment by fwessels** [comment]
That will have to wait a little while (and not until there is ARM support in [c2goasm](https://github.com/minio/c2goasm) that has been used for converting the intrinsics etc. to Golang assembly syntax).

Still need to do more on the performance, we are also thinking of adding support for ndjson as well as lifting the 4 GB limit.

**Comment by detailyang** [comment]
glad to see it which is so cool:)

**Comment by fwessels** [comment]
For now we will just support AVX2, so closing this issue.
