### ISSUE TITLE
Invalid JSON not detected

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#24]
Input: (binary, gunzip) [1f6138064ce740ab0dfc46b12e401fc3b1f430d5.gz](https://github.com/fwessels/simdjson-go/files/3922531/1f6138064ce740ab0dfc46b12e401fc3b1f430d5.gz) Quoted:`	"{\"\":[],\"\":[5\x00]}"`

The 0-byte value is not detected.

**Comment by fwessels** [comment]
Parse succeeds without error. However 0-byte is ignored
