### ISSUE TITLE
Bad parsing while executing stage 2

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#35]
Apparently valid partial file fails: https://files.klauspost.com/compress/bad-file.json.zst

Subsection of working file. Place in `testdata`. Failure:

```
func TestParseND2(t *testing.T) {
	ndjson := getPatchedNdjson("testdata/bad-file.json.zst")
	_, err := ParseND(ndjson, nil)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by fwessels** [comment]
Trailing opening curly brace as last char caused the parsing to fail. Stripping it allows it to succeed.

**Comment by klauspost** [comment]
@fwessels 

The "additional opening curly brace"  is added by the NDJSON converter, it is not present in the input. It is a converted newline.
