### ISSUE TITLE
Big integers overflow

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#47]
Input: `{"o":30886023086020860230}`

Is stored like this on the tape:
```
0 : r	// pointing to 7 (right after last node)
1 : {	// pointing to next Tape location 6 (first node after the scope) 
2 : string "o"
3 : integer -6007465061398243002
5 : }	// pointing to previous Tape location 1 (start of the scope) 
6 : r	// pointing to 0 (start root)
```

This should be stored as a uint type `u` to avoid the overflow.

Alternatively it could be stored as float (since it is more than 56 bits)

**Comment by fwessels** [comment]
We cannot store it as an int because it is too large, so we will store it as an float64.
But we will lose some precision (3.088602308602086e+19), so we will compare against 30886023086020860000.
