### ISSUE TITLE
Small numbers in array

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#49]
```
		{
			name:    "small-number-array",
			js:      `{"G":[0,5e-500,5e-50]}`,
			want:    `{"G":[0,0,5e-50]}`,
			wantErr: false,
		},
```

Getting: `TestParsePassCases() error = Bad parsing while executing stage 2, wantErr false`

**Comment by fwessels** [comment]
5e-500 is detected as too small, causing parse_number to return false.

**Comment by klauspost** [comment]
Yeah, just let it output the closest value `0.0`
