### ISSUE TITLE
cap(pj.Strings) < len(pj.Strings)

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#58]
Something is quite wrong with the strings.

I can reproduce cases where `cap(pj.Strings) < len(pj.Strings)`.

**Comment by fwessels** [comment]
Is this in multi-threaded situations? Is the same object used from multiple threads somehow?

**Comment by fwessels** [comment]
In certain cases a large string could cause the growing of the slice buffer to be too small, leading to writing beyond the capacity of the string buffer
